name: adhub
description: "A Flutter package that simplifies ad integration with a unified API for banner, interstitial, and rewarded ads."
version: 0.0.17
homepage:

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  dio: ^5.9.2
  flutter_hooks: ^0.21.3+1
  in_app_review: ^2.0.12
  package_info_plus: ^10.1.0
  google_mobile_ads: ^8.0.0
  applovin_max: ^4.6.3
  app_tracking_transparency: ^2.0.6
  onesignal_flutter: ^5.5.4
  url_launcher: ^6.3.2
  loading_animation_widget: ^1.2.1
  shared_preferences: ^2.5.5
  flutter_svg: ^2.3.0

flutter:
  assets:
    - assets/logos/dark-logo.svg
    - assets/logos/dark-name.svg
    - assets/logos/light-logo.svg
    - assets/logos/light-name.svg

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0